
#generated by ai to get working



"""
robot/robot_interface.py

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  PLACEHOLDER — Person A (Robot Mechanics & Simulation Lead)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Higher-level robot control layer.  Person B's env_wrapper.py
currently handles action application directly; once you've finalised
the motor model and stability checks this class will be the single
point of truth for all robot control.

Person B will switch to using this when you mark it as ready.
"""

import numpy as np
import mujoco

MAX_WHEEL_VEL = 20.0  # Bug8 fix: must match ctrlrange in robot.xml and env_wrapper.py


class RobotInterface:
    """
    Wraps MuJoCo actuators and sensors into a clean robot-level API.

    Usage (once implemented):
        robot = RobotInterface(model, data)
        robot.apply_action(left=0.8, right=0.8)   # drive forward
        if robot.is_tipped_over():
            episode_end = True
    """

    def __init__(self, model: mujoco.MjModel, data: mujoco.MjData):
        self.model = model
        self.data  = data

    # ----------------------------------------------------------------
    # Action application
    # ----------------------------------------------------------------

    def apply_action(self, left: float, right: float):
        """
        Differential drive.
        left/right ∈ [-1, 1].

        TODO (Person A):
            - Verify gear ratios in robot.xml match the terrain torque needs.
            - If you add front-wheel steering, extend this to accept a steer arg.
            - Consider rate-limiting the action to prevent jerk/instability.
        """
        self.data.ctrl[0] = float(np.clip(left,  -1.0, 1.0)) * MAX_WHEEL_VEL  # motor_fl
        self.data.ctrl[1] = float(np.clip(right, -1.0, 1.0)) * MAX_WHEEL_VEL  # motor_fr
        self.data.ctrl[2] = float(np.clip(left,  -1.0, 1.0)) * MAX_WHEEL_VEL  # motor_rl
        self.data.ctrl[3] = float(np.clip(right, -1.0, 1.0)) * MAX_WHEEL_VEL  # motor_rr

    # ----------------------------------------------------------------
    # State queries
    # ----------------------------------------------------------------

    def is_tipped_over(self, roll_thresh: float = 0.95, pitch_thresh: float = 0.95) -> bool:
        """
        Returns True if the robot has fallen beyond recovery.

        TODO (Person A):
            - Verify these thresholds against robot.xml geometry.
            - A wide, low robot can tolerate more tilt than a tall one.
            - Consider also checking if chassis z-height has dropped
              (robot buried in terrain, not just tilted).
        """
        # placeholder — always returns False until Person A implements this
        return False

    def get_wheel_contacts(self) -> dict:
        """
        Returns a dict of {wheel_name: bool} indicating ground contact.

        TODO (Person A):
            - Iterate self.data.contact to find geom-geom contacts.
            - Match geom names against "tyre_fl", "tyre_fr", etc.
            - Useful for detecting when robot has lost traction.
        """
        return {
            "wheel_fl": False,
            "wheel_fr": False,
            "wheel_rl": False,
            "wheel_rr": False,
        }

    def get_suspension_compression(self) -> dict:
        """
        Returns suspension joint positions if suspension joints exist.

        TODO (Person A):
            - If you add slide joints for suspension (see robot.xml comments),
              read them here for traction-aware reward shaping.
        """
        return {}